<?php
include('../layout/masterpage.php');
?>
<div class="container">
    <table>
        <tr>
            <th>AssetName</th>
            <th>Quantity</th>
            <th>Image</th>
        </tr>
        <tr>
            <td>Peter</td>
            <td>Griffin</td>
            <td>Admin</td>
        </tr>
        <tr>
            <td>Lois</td>
            <td>Griffin</td>
            <td>Executive</td>
        </tr>
        <tr>
            <td>Joe</td>
            <td>Swanson</td>
            <td>Staff</td>
        </tr>
    </table>
</div>