<?php
include('../layout/masterpage.php');
?>
<style>
    <?php
    include('../../assets/css/detail-assets.css');
    ?>
</style>
<div class="container-fluid">
    <a class="button-17" onclick="CreateAssets(true);">เพิ่มครุภัณฑ์</a>
    <table>
        <tr>
            <th>ครุภัณฑ์</th>
            <th>ภาควิชา</th>
            <th>แหล่งที่มาของเงิน</th>
            <th>ปีงบประมาณ</th>
            <th>ชื่อครุภัณฑ์</th>
            <th>รายละเอียด</th>
            <th>หน่วยนับ</th>
            <th>วันที่รับเข้าคลัง</th>
            <th>มูลค่าครุภัณฑ์</th>
            <th>เลขที่ใบส่งของ</th>
            <th>ผู้ขาย</th>
            <th>หมายเลขซีเรียล</th>
            <th>วันหมดประกัน</th>
            <th>ประเภท</th>
            <th>สถานะ</th>
            <th>ที่อยู่</th>
            <th>QR-CODE</th>
            <th>รูปภาพ</th>
            <th>แก้ไข</th>
        </tr>
        <?php
            include('../../assets/db/showassets.php');
        ?>
    </table>
</div>